version: "3.9"
services:
  fastapi:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:8000
    volumes:
      - type: bind
        source: ./data
        target: /app/data

      - type: volume
        source : data3
        target : /app/data3

# volumes:
#   data3:
#     external: true